# Sorting with Numpy

In [1]:
import numpy as np

In [2]:
variable = np.array([3,8,1,5,6,4,9])
variable

array([3, 8, 1, 5, 6, 4, 9])

In [3]:
np.sort(variable)

array([1, 3, 4, 5, 6, 8, 9])

In [4]:
variable2 = np.sort(variable)
variable2

array([1, 3, 4, 5, 6, 8, 9])

In [5]:
variable_2dim = np.random.normal(30, 10, (4,4))
variable_2dim

array([[32.71245431, 12.62878501, 30.55169546, 27.80525242],
       [24.51868058, 28.74575209, 15.28325543,  7.01282263],
       [19.38582747, 26.76204635, 23.55615692, 24.89133052],
       [37.76282226, 38.96339045, 34.28222516, 28.16544217]])

In [6]:
sorted_2d = np.sort(variable_2dim, axis=0)
sorted_2d

array([[19.38582747, 12.62878501, 15.28325543,  7.01282263],
       [24.51868058, 26.76204635, 23.55615692, 24.89133052],
       [32.71245431, 28.74575209, 30.55169546, 27.80525242],
       [37.76282226, 38.96339045, 34.28222516, 28.16544217]])

In [8]:
orted_2d = np.sort(variable_2dim, axis=1)
orted_2d

array([[12.62878501, 27.80525242, 30.55169546, 32.71245431],
       [ 7.01282263, 15.28325543, 24.51868058, 28.74575209],
       [19.38582747, 23.55615692, 24.89133052, 26.76204635],
       [28.16544217, 34.28222516, 37.76282226, 38.96339045]])