# Numpy functions concatenate

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

In [3]:
array1

array([1, 2, 3, 4])

In [4]:
array2

array([5, 6, 7, 8])

In [5]:
np.concatenate([array1, array2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
array3 = np.arange(0,6).reshape((2,3))
array3

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
array4 = np.array([[6,7,8], [9,10,11]])
array4

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.concatenate([array3,array4])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.concatenate([array3,array4], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [10]:
np.concatenate([array1, array3])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [11]:
np.concatenate([array1, array3], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1