# Numpy functions split

In [1]:
import numpy as np

In [2]:
array = np.array([1,3,5,20,20,2,4,6])

In [3]:
array

array([ 1,  3,  5, 20, 20,  2,  4,  6])

In [4]:
np.split(array, [3, 5])

[array([1, 3, 5]), array([20, 20]), array([2, 4, 6])]

In [6]:
a,b,c = np.split(array, [3, 5])
a


array([1, 3, 5])

In [7]:
b

array([20, 20])

In [8]:
c

array([2, 4, 6])

In [9]:
np.split(array, 4)

[array([1, 3]), array([ 5, 20]), array([20,  2]), array([4, 6])]

In [10]:
np.split(array, 7)

ValueError: array split does not result in an equal division

## 2 dimensional splits

In [11]:
array = np.arange(20).reshape(5,4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
array.ndim

2

In [13]:
np.split(array, [1, 3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [14]:
a,b,c = np.split(array, [1, 3])
a

array([[0, 1, 2, 3]])

In [15]:
b

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
c

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
np.split(array, [1, 3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [18]:
np.hsplit(array, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13],
        [17]]),
 array([[ 2],
        [ 6],
        [10],
        [14],
        [18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [20]:
np.vsplit(array, 5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]