# Solving Equations with Numpy

2x + 4y = 14, 4x - 4y = 4
Solve: x = 3, y = 2

In [1]:
import numpy as np

In [3]:
coefficient = np.array([[2, 4], [4, -4]])
coefficient

array([[ 2,  4],
       [ 4, -4]])

In [4]:
output = np.array([14,4])
output

array([14,  4])

In [5]:
np.linalg.solve(coefficient, output)

array([3., 2.])