# Airthmetic Operations in Numpy

In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)

In [3]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Arithmetic Operators are: +, -, *, /, %, **, //

In [4]:
array - 3

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [5]:
array * 10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [6]:
array / 10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [7]:
((array * 10) + 5) / 20

array([0.75, 1.25, 1.75, 2.25, 2.75, 3.25, 3.75, 4.25, 4.75, 5.25])

In [8]:
array * array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
array /array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.subtract(array, 2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [11]:
np.multiply(array, 10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [12]:
array ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [13]:
np.power(array, 3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [14]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [15]:
array % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [16]:
np.mod(array, 5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [17]:
np.sin(array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [18]:
np.cos(array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [19]:
np.log(array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [20]:
np.log10(array)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])