# Numpy comparison operations

Conditional operators in Python >, < , >=, <=, ==

In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [5]:
condition = array<=5
condition

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [6]:
array[condition]

array([1, 2, 3, 4, 5])

In [7]:
new_condition = (array !=8) & (array >= 4)
new_condition

array([False, False, False,  True,  True,  True,  True, False,  True,
        True])

In [8]:
array[new_condition]

array([ 4,  5,  6,  7,  9, 10])