# Mixed Indexing in Numpy

In [1]:
import numpy as np

In [2]:
example = np.arange(1,17).reshape(4,4)
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [3]:
example[1, [1,3]]

array([6, 8])

In [5]:
example[[0,3], 1]

array([ 2, 14])

In [6]:
example[0:, [1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [7]:
example[1:3, [1,3]]

array([[ 6,  8],
       [10, 12]])