# Advanced indexing in Numpy - 1D

In [1]:
import numpy as np

In [2]:
advanced = np.arange(0, 50, 5)
advanced

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [3]:
advanced[1]

5

In [4]:
advanced[3]

15

In [5]:
advanced[5]

25

In [6]:
[advanced[1], advanced[3], advanced[5]]

[5, 15, 25]

In [7]:
indexes = [1,3,5]

In [8]:
advanced[indexes]

array([ 5, 15, 25])

In [9]:
array = np.array([1,3,5])
advanced[array]

array([ 5, 15, 25])

# Advanced Indexing in Numpy - 2D

In [10]:
variable = np.zeros((10, 10), dtype='int')
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
variable.shape

(10, 10)

In [12]:
variable.shape[0]

10

In [14]:
row = variable.shape[0]
for i in range(row):
    variable[i] = i
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [15]:
list1 = [1,4,6,9]
variable[list1]

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [16]:
list2 = [8,4,2,7,3]
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [17]:
example = np.arange(1,17).reshape(4,4)
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [18]:
example[[0,3], [1,2]]

array([ 2, 15])

In [19]:
row = [0,2,3,1]
column = [3,0,2,1]
example[row, column]

array([ 4,  9, 15,  6])