# Assigning values to one dimensional arrays

In [1]:
import numpy as np

In [3]:
variable = np.array([0,1,2,3,7,5,6,9,8,9])
variable

array([0, 1, 2, 3, 7, 5, 6, 9, 8, 9])

In [4]:
variable[4]

7

In [5]:
variable[4] = 4
variable[7] = 7
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
variable[0:5]

array([0, 1, 2, 3, 4])

In [7]:
variable[0:5] = 10

In [8]:
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [9]:
variable[5:]

array([5, 6, 7, 8, 9])

In [10]:
variable[5:] = 20,30,40,50,60
variable

array([10, 10, 10, 10, 10, 20, 30, 40, 50, 60])

# Assigning values to a 2D array

In [11]:
example = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
example

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
example[1,1]

50

In [13]:
example[1,1] = 100
example

array([[ 10,  20,  30],
       [ 40, 100,  60],
       [ 70,  80,  90]])

In [14]:
example[:, 2]

array([30, 60, 90])

In [15]:
example[:, 2] = 100
example

array([[ 10,  20, 100],
       [ 40, 100, 100],
       [ 70,  80, 100]])

In [16]:
example[0::2, 0:2]

array([[10, 20],
       [70, 80]])

In [17]:
example[0::2, 0:2] = 100
example

array([[100, 100, 100],
       [ 40, 100, 100],
       [100, 100, 100]])

In [18]:
example[0]

array([100, 100, 100])

In [19]:
example[0]   =10, 20, 30
example

array([[ 10,  20,  30],
       [ 40, 100, 100],
       [100, 100, 100]])