# Slicing a one dimensional numpy array

In [1]:
import numpy as np

In [2]:
example = np.arange(10,20)
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## Syntax
variable_name[start:stop:step]

In [4]:
example[2:8]

array([12, 13, 14, 15, 16, 17])

In [6]:
example[2:-2]

array([12, 13, 14, 15, 16, 17])

In [8]:
example[3::2]

array([13, 15, 17, 19])

In [9]:
example[:8:3]

array([10, 13, 16])

In [10]:
example[::4]

array([10, 14, 18])

# Slicing a two dimensional array

In [11]:
array = np.arange(30).reshape(6,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## Syntax
variable_name[start:stop:step , start:stop:step]

In [12]:
array[2, :]

array([10, 11, 12, 13, 14])

In [13]:
array[2]

array([10, 11, 12, 13, 14])

In [14]:
array[:, 2]

array([ 2,  7, 12, 17, 22, 27])

In [15]:
array[2:5, 1:4]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

In [16]:
array[0::2, 0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])