# Numpy array creation using the random function

In [1]:
import numpy as np

In [3]:
np.random.rand(6)

array([0.67874066, 0.12736599, 0.09615413, 0.69344387, 0.22842819,
       0.87469947])

In [4]:
np.random.randn(5)

array([ 0.25759753, -0.29899761,  0.82195919, -0.72749325,  1.23830066])

In [5]:
np.random.normal(20, 5, (4,4))

array([[16.28299261, 27.82120376, 25.74227021, 22.78307558],
       [25.73173587, 16.56767429, 21.94810702, 24.82278388],
       [18.61547569, 21.59728798, 13.67383751, 17.2260276 ],
       [22.997645  , 19.02564847, 17.43050257, 10.55078239]])