# Creating Numpy Arrays using the Array()

In [1]:
import numpy as np

In [2]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [3]:
test_variable = [2.8,5,7,6]

Checking the data types in the list

In [4]:
print(type(test_variable[0]))
print(type(test_variable[1]))

<class 'float'>
<class 'int'>


In [5]:
new_variable = np.array([2.8,5,7,6])
new_variable

array([2.8, 5. , 7. , 6. ])

In [6]:
print(type(new_variable[0]))
print(type(new_variable[1]))

<class 'numpy.float64'>
<class 'numpy.float64'>


In [7]:
new_variable2 = np.array([2.8,5,7,6], dtype='int')
new_variable2

array([2, 5, 7, 6])