# Numpy array creation with the Eye function

In [1]:
import numpy as np

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [4]:
np.eye(3,2, dtype='bool')

array([[ True, False],
       [False,  True],
       [False, False]])